node {
   env.BUILD_DIR="/root/build-workspace/"
   env.MODULE="web-demo"
   env.HOST="web-demo.com"
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/zouyingjie/mooc-k8s-demo-docker.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.
      mvnHome = tool 'M3'
   }
   stage('Maven Build') {
       sh "mvn -pl ${MODULE} -am clean package"
   }
   stage('Build Image') {
      sh "/root/script/build-image-web.sh"
   }

   stage("Deploy Image") {
       sh "/root/script/deploy.sh"
   }
}